export const API_SUCCESS_CODES = [
  "OK",
  "RESULT_ACCEPTED",
  "LEADERBOARD_READ",
  "AUTH_LINK_REQUESTED",
  "SIGNED_IN",
  "SIGNED_OUT",
  "PROFILE_UPDATED",
  "MISSION_PREPARED",
  "MISSION_LOCKED",
  "MISSION_TRAFFIC_UPDATED",
  "MISSION_LEASE_RELEASED",
] as const;

export const API_ERROR_CODES = [
  "NOT_FOUND",
  "METHOD_NOT_ALLOWED",
  "INVALID_REQUEST",
  "REQUEST_TOO_LARGE",
  "ORIGIN_REQUIRED",
  "ORIGIN_MISMATCH",
  "CSRF_INVALID",
  "IDEMPOTENCY_KEY_REQUIRED",
  "IDEMPOTENCY_KEY_INVALID",
  "AUTH_REQUIRED",
  "AUTH_LINK_INVALID",
  "FORBIDDEN",
  "RATE_LIMITED",
  "LIMITER_UNAVAILABLE",
  "ADMISSION_DENIED",
  "BROKER_UNAVAILABLE",
  "MISSION_RECONFIRM_REQUIRED",
  "MISSION_PREPARATION_INVALID",
  "MISSION_PREPARATION_EXPIRED",
  "MISSION_AIRCRAFT_STALE",
  "MISSION_AIRCRAFT_UNAVAILABLE",
  "MISSION_DESTINATION_INVALID",
  "MISSION_CAPACITY_UNAVAILABLE",
  "MISSION_IDEMPOTENCY_CONFLICT",
  "MISSION_RESULT_INVALID",
  "MISSION_COMMIT_FAILED",
  "INTERNAL_ERROR",
] as const;

export type ApiSuccessCode = (typeof API_SUCCESS_CODES)[number];
export type ApiErrorCode = (typeof API_ERROR_CODES)[number];
export type ApiCode = ApiSuccessCode | ApiErrorCode;
