import { describe, expect, it } from "vitest";

import {
  ACTIVE_FLIGHT_GLOBAL_LIMIT,
  ACTIVE_FLIGHT_MAX_RESERVE,
  ACTIVE_FLIGHT_REFRESH_SECONDS,
  ACTIVE_FLIGHT_RESERVE_PER_LEASE,
  ACTIVE_FLIGHT_WARNING,
  ANONYMOUS_REFRESH_SECONDS,
  CONSERVATION_ANONYMOUS_REFRESH_SECONDS,
  CONSERVATION_SIGNED_BROWSE_REFRESH_SECONDS,
  CONSERVATION_THRESHOLD_REQUESTS,
  DAILY_ADMITTED_REQUEST_LIMIT,
  KILL_SWITCH_THRESHOLD_REQUESTS,
  READ_ONLY_THRESHOLD_REQUESTS,
  SIGNED_BROWSE_REFRESH_SECONDS,
  TRAFFIC_FRESH_SECONDS,
} from "./limits";

describe("launch limits", () => {
  it("keeps the approved thresholds, flight capacity, and reserve formula exact", () => {
    expect(DAILY_ADMITTED_REQUEST_LIMIT).toBe(100_000);
    expect(CONSERVATION_THRESHOLD_REQUESTS).toBe(70_000);
    expect(READ_ONLY_THRESHOLD_REQUESTS).toBe(90_000);
    expect(KILL_SWITCH_THRESHOLD_REQUESTS).toBe(100_000);
    expect(ACTIVE_FLIGHT_WARNING).toBe(8);
    expect(ACTIVE_FLIGHT_GLOBAL_LIMIT).toBe(10);
    expect(ACTIVE_FLIGHT_RESERVE_PER_LEASE).toBe(150);
    expect(ACTIVE_FLIGHT_MAX_RESERVE).toBe(1_500);
    expect([
      ANONYMOUS_REFRESH_SECONDS,
      SIGNED_BROWSE_REFRESH_SECONDS,
      ACTIVE_FLIGHT_REFRESH_SECONDS,
    ]).toEqual([30, 20, 12]);
    expect([
      CONSERVATION_ANONYMOUS_REFRESH_SECONDS,
      CONSERVATION_SIGNED_BROWSE_REFRESH_SECONDS,
      ACTIVE_FLIGHT_REFRESH_SECONDS,
    ]).toEqual([60, 40, 12]);
    // Frugal ADS-B: cache-fresh window is the upstream-fetch gate; keep it locked.
    expect(TRAFFIC_FRESH_SECONDS).toBe(30);
  });
});
