export const ANONYMOUS_REFRESH_SECONDS = 15;
export const SIGNED_BROWSE_REFRESH_SECONDS = 8;
export const ACTIVE_FLIGHT_REFRESH_SECONDS = 12;

export const CONSERVATION_ANONYMOUS_REFRESH_SECONDS = 30;
export const CONSERVATION_SIGNED_BROWSE_REFRESH_SECONDS = 15;

export const TRAFFIC_MIN_RADIUS_NM = 10;
export const TRAFFIC_MAX_RADIUS_NM = 250;
export const TRAFFIC_FRESH_SECONDS = SIGNED_BROWSE_REFRESH_SECONDS;
export const TRAFFIC_EXPIRE_SECONDS = 120;
export const TRAFFIC_RETRY_BASE_SECONDS = 15;
export const TRAFFIC_RETRY_MAX_SECONDS = 60;
export const TRAFFIC_CACHE_MAX_REGIONS = 32;
export const TRAFFIC_REGION_CELL_DEGREES = 0.25;
export const TRAFFIC_PROVIDER_RADIUS_STEP_NM = 25;
export const TRAFFIC_PROVIDER_TIMEOUT_MS = 12_000;
export const TRAFFIC_PROVIDER_MAX_RESPONSE_BYTES = 1_048_576;

export const DAILY_ADMITTED_REQUEST_LIMIT = 100_000;
export const CONSERVATION_THRESHOLD_PERCENT = 70;
export const READ_ONLY_THRESHOLD_PERCENT = 90;
export const KILL_SWITCH_THRESHOLD_PERCENT = 100;

export const ACTIVE_FLIGHT_USER_LIMIT = 1;
export const ACTIVE_FLIGHT_GLOBAL_LIMIT = 10;
export const ACTIVE_FLIGHT_WARNING = 8;
export const ACTIVE_FLIGHT_LEASE_SECONDS = 45;

export const AUTH_REQUEST_BODY_MAX_BYTES = 4_096;
export const AUTH_CONSUME_BODY_MAX_BYTES = 1_024;
export const AUTH_MAGIC_LINK_TTL_MS = 15 * 60 * 1_000;
export const AUTH_SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;
export const AUTH_EMAIL_RATE_WINDOW_MS = 60 * 60 * 1_000;
export const AUTH_EMAIL_RATE_MAXIMUM = 3;
export const DEFAULT_PROFILE_RADIUS_NM = 80;

// Owner-approved Task 4 contract: protect each flight present at the read-only
// transition for the 30-minute mission reachability horizon at normal cadence.
export const ACTIVE_FLIGHT_PROTECTION_WINDOW_SECONDS = 30 * 60;
export const ACTIVE_FLIGHT_RESERVE_PER_LEASE = Math.ceil(
  ACTIVE_FLIGHT_PROTECTION_WINDOW_SECONDS / ACTIVE_FLIGHT_REFRESH_SECONDS,
);
export const ACTIVE_FLIGHT_MAX_RESERVE =
  ACTIVE_FLIGHT_GLOBAL_LIMIT * ACTIVE_FLIGHT_RESERVE_PER_LEASE;

export const CONSERVATION_THRESHOLD_REQUESTS =
  (DAILY_ADMITTED_REQUEST_LIMIT * CONSERVATION_THRESHOLD_PERCENT) / 100;
export const READ_ONLY_THRESHOLD_REQUESTS =
  (DAILY_ADMITTED_REQUEST_LIMIT * READ_ONLY_THRESHOLD_PERCENT) / 100;
export const KILL_SWITCH_THRESHOLD_REQUESTS =
  (DAILY_ADMITTED_REQUEST_LIMIT * KILL_SWITCH_THRESHOLD_PERCENT) / 100;
