export const ANONYMOUS_REFRESH_SECONDS = 15;
export const SIGNED_BROWSE_REFRESH_SECONDS = 8;
export const ACTIVE_FLIGHT_REFRESH_SECONDS = 12;

export const CONSERVATION_ANONYMOUS_REFRESH_SECONDS = 30;
export const CONSERVATION_SIGNED_BROWSE_REFRESH_SECONDS = 15;

export const DAILY_ADMITTED_REQUEST_LIMIT = 100_000;
export const CONSERVATION_THRESHOLD_PERCENT = 70;
export const READ_ONLY_THRESHOLD_PERCENT = 90;
export const KILL_SWITCH_THRESHOLD_PERCENT = 100;

export const ACTIVE_FLIGHT_USER_LIMIT = 1;
export const ACTIVE_FLIGHT_GLOBAL_LIMIT = 10;
export const ACTIVE_FLIGHT_WARNING = 8;
export const ACTIVE_FLIGHT_LEASE_SECONDS = 45;

// Owner-approved Task 4 contract: protect each flight present at the read-only
// transition for the 30-minute mission reachability horizon at normal cadence.
export const ACTIVE_FLIGHT_PROTECTION_WINDOW_SECONDS = 30 * 60;
export const ACTIVE_FLIGHT_RESERVE_PER_LEASE = Math.ceil(
  ACTIVE_FLIGHT_PROTECTION_WINDOW_SECONDS / ACTIVE_FLIGHT_REFRESH_SECONDS,
);
export const ACTIVE_FLIGHT_MAX_RESERVE =
  ACTIVE_FLIGHT_GLOBAL_LIMIT * ACTIVE_FLIGHT_RESERVE_PER_LEASE;

export const CONSERVATION_THRESHOLD_REQUESTS =
  (DAILY_ADMITTED_REQUEST_LIMIT * CONSERVATION_THRESHOLD_PERCENT) / 100;
export const READ_ONLY_THRESHOLD_REQUESTS =
  (DAILY_ADMITTED_REQUEST_LIMIT * READ_ONLY_THRESHOLD_PERCENT) / 100;
export const KILL_SWITCH_THRESHOLD_REQUESTS =
  (DAILY_ADMITTED_REQUEST_LIMIT * KILL_SWITCH_THRESHOLD_PERCENT) / 100;
